In [11]:
import pandas as pd

dfEtnia = pd.read_csv('dados_prontos/etnia_cadunico_tratado.csv')


dfEtnia = dfEtnia[dfEtnia['RI'] == 'Guamá']
dfEtniaCenso = dfEtnia[(dfEtnia['Ano'] == 2013) | (dfEtnia['Ano'] == 2022)]
dfEtniaCenso

,Codigo,Municipio,Brancos,Pretos,Amarelos,Pardos,Indigenas,NoData,Ano,RI
491,150240,CASTANHAL,10499,3258,229,87141,52,1311,2013,Guamá
500,150240,CASTANHAL,13981,4310,369,91126,52,16,2022,Guamá
519,150260,COLARES,1171,158,32,6414,16,44,2013,Guamá
528,150260,COLARES,1553,304,44,7652,6,1,2022,Guamá
617,150290,CURUÇÁ,1892,327,72,24352,6,332,2013,Guamá
626,150290,CURUÇÁ,3611,566,155,27544,86,3,2022,Guamá
729,150320,IGARAPÉ-AÇU,788,265,37,21666,14,344,2013,Guamá
738,150320,IGARAPÉ-AÇU,1621,416,64,25170,11,3,2022,Guamá
757,150340,INHANGAPI,369,590,6,6246,6,115,2013,Guamá
766,150340,INHANGAPI,430,513,10,6961,8,1,2022,Guamá
897,150410,MAGALHÃES BARATA,367,72,5,6019,4,65,2013,Guamá
906,150410,MAGALHÃES BARATA,563,61,18,5797,3,0,2022,Guamá
927,150430,MARACANÃ,1503,114,28,23968,15,1,2022,Guamá
936,150430,MARACANÃ,1572,139,17,22306,4,163,2013,Guamá
939,150440,MARAPANIM,2390,425,13,15650,46,97,2013,Guamá
948,150440,MARAPANIM,2417,298,59,16869,30,1,2022,Guamá
1512,150650,SANTA IZABEL DO PARÁ,1741,746,37,34551,12,221,2013,Guamá
1521,150650,SANTA IZABEL DO PARÁ,1892,724,75,33517,12,6,2022,Guamá
1554,150660,SANTA MARIA DO PARÁ,1077,408,44,16211,55,88,2013,Guamá
1563,150660,SANTA MARIA DO PARÁ,1432,392,50,15680,110,1,2022,Guamá
1612,150700,SANTO ANTÔNIO DO TAUÁ,1680,280,52,16005,15,213,2013,Guamá
1621,150700,SANTO ANTÔNIO DO TAUÁ,1536,261,85,19386,5,1,2022,Guamá
1626,150710,SÃO CAETANO DE ODIVELAS,904,205,21,12283,1,0,2022,Guamá
1635,150710,SÃO CAETANO DE ODIVELAS,561,183,8,12220,2,157,2013,Guamá
1654,150720,SÃO DOMINGOS DO CAPIM,522,463,81,25009,6,5,2022,Guamá
1663,150720,SÃO DOMINGOS DO CAPIM,732,848,21,24543,5,300,2013,Guamá
1686,150740,SÃO FRANCISCO DO PARÁ,908,125,26,11095,7,1,2022,Guamá
1692,150740,SÃO FRANCISCO DO PARÁ,936,109,13,10581,13,142,2013,Guamá
1707,150746,SÃO JOÃO DA PONTA,255,30,5,4282,3,50,2013,Guamá
1712,150746,SÃO JOÃO DA PONTA,404,79,10,4976,1,2,2022,Guamá
1749,150760,SÃO MIGUEL DO GUAMÁ,1944,624,32,33751,9,553,2013,Guamá
1759,150760,SÃO MIGUEL DO GUAMÁ,1537,732,141,34919,15,5,2022,Guamá
1836,150796,TERRA ALTA,439,138,38,9801,42,2,2022,Guamá
1846,150796,TERRA ALTA,364,152,1,7975,18,129,2013,Guamá
1961,150820,VIGIA,1842,542,53,28391,90,147,2013,Guamá
1965,150820,VIGIA,3124,774,181,34306,61,7,2022,Guamá

In [13]:
dfSexo = pd.read_csv('dados_prontos/sexo_cadunico_tratado.csv')

dfSexoCenso = dfSexo[(dfSexo['Ano'] == 2013) | (dfSexo['Ano'] == 2022)]
dfSexoCenso

      Codigo         Municipio  Homens  Mulheres   Ano         RI
3     150010        ABAETETUBA   62504     70334  2022  Tocantins
12    150010        ABAETETUBA   47547     57830  2013  Tocantins
17    150013   ABEL FIGUEIREDO    2592      3060  2022  Rio Capim
26    150013   ABEL FIGUEIREDO    2222      2609  2013  Rio Capim
31    150020             ACARÁ   22480     25332  2022  Tocantins
...      ...               ...     ...       ...   ...        ...
1983  150830             VISEU   22674     23329  2022  Rio Caeté
1988  150835  VITÓRIA DO XINGU    3547      3700  2013      Xingu
1997  150835  VITÓRIA DO XINGU    5339      6195  2022      Xingu
2004  150840          XINGUARA   11446     14885  2022   Araguaia
2013  150840          XINGUARA    9464     11893  2013   Araguaia

[288 rows x 6 columns]

In [14]:
dfIdade = pd.read_csv('dados_prontos/faixa_etaria_cadunico_tratado.csv')

dfIdade

,Codigo,Municipio,0-3,4-6,7-15,16-17,18-24,25-34,35-39,40-44,45-49,50-54,55-59,60-64,64+,Total,Ano,RI
0,150010,ABAETETUBA,NaN,NaN,23682,5901,17267,16374,6321,5287,4110,3211,2520,1671,2455,88799,2012,Tocantins
1,150010,ABAETETUBA,8003.0,7623.0,22397,5209,16639,22497,9846,7485,9821,6690,5278,3979,6896,132363,2026,Tocantins
2,150010,ABAETETUBA,8053.0,7618.0,22410,5209,16699,22538,9858,7452,9804,6617,5285,3956,6815,132314,2026,Tocantins
3,150010,ABAETETUBA,8102.0,7600.0,22397,5238,16713,22575,9816,7461,9723,6573,5304,3895,6767,132164,2026,Tocantins
4,150010,ABAETETUBA,8121.0,7621.0,22390,5232,16695,22574,9811,7453,9641,6485,5324,3814,6676,131837,2026,Tocantins
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24173,150840,XINGUARA,NaN,NaN,4969,1049,2546,2538,1205,953,743,503,363,373,1332,16574,2012,Araguaia
24174,150840,XINGUARA,NaN,NaN,4959,1061,2530,2521,1205,943,745,495,347,382,1322,16510,2012,Araguaia
24175,150840,XINGUARA,NaN,NaN,4955,1081,2500,2528,1199,951,734,496,344,384,1317,16489,2012,Araguaia
24176,150840,XINGUARA,NaN,NaN,4979,1079,2491,2530,1198,954,725,489,340,391,1305,16481,2012,Araguaia
24177,150840,XINGUARA,NaN,NaN,5018,1065,2476,2530,1195,949,716,488,338,395,1297,16467,2012,Araguaia