In [65]:
import pandas as pd

dfEtnia = pd.read_csv('dados_prontos/etnia_cadunico_tratado.csv')

dfEtniaCenso = dfEtnia[(dfEtnia['Ano'] == 2013) | (dfEtnia['Ano'] == 2022)]
dfEtniaCenso.rename(columns={'Brancos':'Branca','Pretos':'Preta','Amarelos':'Amarela','Pardos':'Parda','Indigenas':'Indigena'},inplace=True)
dfEtniaCenso

,Codigo,Municipio,Branca,Preta,Amarela,Parda,Indigena,NoData,Ano,RI
3,150010,ABAETETUBA,17519,6910,355,107976,71,7,2022,Tocantins
12,150010,ABAETETUBA,14931,6305,267,82803,107,964,2013,Tocantins
17,150013,ABEL FIGUEIREDO,1181,276,13,4181,1,0,2022,Rio Capim
26,150013,ABEL FIGUEIREDO,653,190,7,3903,1,77,2013,Rio Capim
31,150020,ACARÁ,2645,2723,130,42255,55,4,2022,Tocantins
...,...,...,...,...,...,...,...,...,...,...
1983,150830,VISEU,842,371,105,44668,16,1,2022,Rio Caeté
1988,150835,VITÓRIA DO XINGU,1081,494,36,5583,39,14,2013,Xingu
1997,150835,VITÓRIA DO XINGU,1482,702,97,9050,201,2,2022,Xingu
2004,150840,XINGUARA,2566,992,128,22611,30,4,2022,Araguaia
2013,150840,XINGUARA,3283,1389,62,16292,41,290,2013,Araguaia

In [66]:
dfEtniaCenso.to_csv('panoramaCadunico/etnia_cadunico.csv',index=False)

In [67]:
dfSexo = pd.read_csv('dados_prontos/sexo_cadunico_tratado.csv')

dfSexoCenso = dfSexo[(dfSexo['Ano'] == 2013) | (dfSexo['Ano'] == 2022)]
dfSexoCenso.to_csv('panoramaCadunico/sexo_cadunico.csv',index=False)

In [68]:
dfIdade = pd.read_csv('dados_prontos/faixa_etaria_cadunico_tratado.csv')

dfIdadeCenso = dfIdade[(dfIdade['Ano'] == 2013) | (dfIdade['Ano'] == 2022)]
dfIdadeCenso

,Codigo,Municipio,0-3,4-6,7-15,16-17,18-24,25-34,35-39,40-44,45-49,50-54,55-59,60-64,64+,Total,Ano,RI
3,150010,ABAETETUBA,8707.0,7680.0,22673,5148,19082,24229,9988,8686,7260,5893,4607,3265,5620,132838,2022,Tocantins
12,150010,ABAETETUBA,NaN,NaN,24454,6132,16457,16663,6391,5538,4386,3454,2695,1931,2967,91068,2013,Tocantins
17,150013,ABEL FIGUEIREDO,387.0,394.0,1088,233,737,769,380,360,291,243,230,183,357,5652,2022,Rio Capim
26,150013,ABEL FIGUEIREDO,NaN,NaN,1145,250,627,763,330,263,211,177,133,84,99,4082,2013,Rio Capim
31,150020,ACARÁ,3324.0,3244.0,10350,2396,6218,7446,3193,2827,2354,2098,1652,1010,1700,47812,2022,Tocantins
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1983,150830,VISEU,2998.0,3337.0,11014,2553,6342,6999,3294,2687,2007,1582,1231,786,1173,46003,2022,Rio Caeté
1988,150835,VITÓRIA DO XINGU,NaN,NaN,1843,410,1101,1158,506,409,328,211,147,106,189,6408,2013,Xingu
1997,150835,VITÓRIA DO XINGU,945.0,793.0,2511,524,1400,1657,723,675,552,453,392,280,629,11534,2022,Xingu
2004,150840,XINGUARA,1754.0,1755.0,5141,1175,3109,3477,1715,1524,1286,1093,1034,901,2367,26331,2022,Araguaia
2013,150840,XINGUARA,NaN,NaN,5257,1104,2901,2972,1309,1073,875,629,490,401,1461,18472,2013,Araguaia

In [69]:
dfIdadeCenso.to_csv('panoramaCadunico/faixa_etaria_cadunico.csv',index=False)

In [70]:
dfUrbe = pd.read_csv('dados_prontos/urbano_rural_cadunico_tratado.csv')

dfUrbeCenso = dfUrbe[(dfUrbe['Ano'] == 2013) | (dfUrbe['Ano'] == 2022)]
dfUrbe.to_csv('panoramaCadunico/urbano_rural_cadunico.csv',index=False)