In [44]:
#   Pessoas cadastradas no Cadastro Único - por sexo  

import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))
#magia maluca que faz from utils import helper funcionar ^
import pandas as pd
from utils import helper


df = pd.read_csv('dados_brutos/sexo_cadunico.csv')

df.rename(columns={'Código':'Codigo','Unidade Territorial':'Municipio','Referência':'Data',
'Número de pessoas do sexo masculino cadastradas no Cadastro Único':'Homens',
'Número de pessoas do sexo feminino cadastradas no Cadastro Único':'Mulheres'},inplace=True)


df = helper.data_to_ano(df)
df = helper.codigo_to_ri(df)

df = df[df["Mes"] == 12]
df.drop(columns=['UF','Data','Mes'],inplace=True)

df

       Codigo   Municipio  Homens  Mulheres   Ano         RI
10     150010  ABAETETUBA   58440     70994  2025  Tocantins
28     150010  ABAETETUBA   59279     70507  2024  Tocantins
40     150010  ABAETETUBA   64150     72134  2023  Tocantins
50     150010  ABAETETUBA   62504     70334  2022  Tocantins
58     150010  ABAETETUBA   53959     65039  2021  Tocantins
...       ...         ...     ...       ...   ...        ...
24127  150840    XINGUARA    9724     12242  2016   Araguaia
24141  150840    XINGUARA    9340     11671  2015   Araguaia
24151  150840    XINGUARA   10522     12996  2014   Araguaia
24163  150840    XINGUARA    9464     11893  2013   Araguaia
24173  150840    XINGUARA    8382     10459  2012   Araguaia

[2015 rows x 6 columns]

In [45]:
df.to_csv('dados_prontos/sexo_cadunico_tratado.csv',index=False)

In [46]:
#Pessoas inscritas no Cadastro Único - por raça/cor

df = pd.read_csv('dados_brutos/etnia_cadunico.csv')

df.rename(columns={'Código':'Codigo','Unidade Territorial':'Municipio','Referência':'Data',
                   'Quantidade de pessoas brancas inscritas no Cadastro Único':'Brancos',
                   'Quantidade de pessoas pretas inscritas no Cadastro Único':'Pretos',
                   'Quantidade de pessoas amarelas inscritas no Cadastro Único':'Amarelos',
                   'Quantidade de pessoas pardas inscritas no Cadastro Único':'Pardos',
                   'Quantidade de pessoas indígenas inscritas no Cadastro Único':'Indigenas',
                   'Quantidade de pessoas sem informação sobre raça/cor inscritas no Cadastro Único':'NoData'},inplace=True)

df = helper.data_to_ano(df)
df = helper.codigo_to_ri(df)

df = df[df["Mes"] == 12]
df.drop(columns=['UF','Data','Mes'],inplace=True)

df

,Codigo,Municipio,Brancos,Pretos,Amarelos,Pardos,Indigenas,NoData,Ano,RI
10,150010,ABAETETUBA,17050,7130,329,104856,67,2,2025,Tocantins
28,150010,ABAETETUBA,16892,6569,341,105911,71,2,2024,Tocantins
40,150010,ABAETETUBA,17864,6969,374,111004,68,5,2023,Tocantins
50,150010,ABAETETUBA,17519,6910,355,107976,71,7,2022,Tocantins
58,150010,ABAETETUBA,15476,6137,292,97017,71,5,2021,Tocantins
...,...,...,...,...,...,...,...,...,...,...
24127,150840,XINGUARA,2560,1027,60,18228,31,60,2016,Araguaia
24141,150840,XINGUARA,2665,1060,63,17126,27,70,2015,Araguaia
24151,150840,XINGUARA,3428,1409,69,18430,38,144,2014,Araguaia
24163,150840,XINGUARA,3283,1389,62,16292,41,290,2013,Araguaia
24173,150840,XINGUARA,3055,1493,50,14119,54,70,2012,Araguaia

In [47]:

df.to_csv('dados_prontos/etnia_cadunico_tratado.csv',index=False)

In [48]:
#Pessoas cadastradas no Cadastro Único - por faixa etária 

df = pd.read_csv('dados_brutos/faixa_etaria_cadunico.csv')

df.rename(columns={'Código':'Codigo','Unidade Territorial':'Municipio','Referência':'Data',
                   'Número de pessoas com idade entre 0 e 3 anos cadastradas no Cadastro Único':'0-3',
                   'Número de pessoas com idade entre 4 e 6 anos cadastradas no Cadastro Único':'4-6',
                   'Número de pessoas com idade entre 7 e 15 anos cadastradas no Cadastro Único':'7-15',
                   'Número de pessoas com idade entre 16 e 17 anos cadastradas no Cadastro Único':'16-17',
                   'Número de pessoas com idade entre 18 e 24 anos cadastradas no Cadastro Único':'18-24',
                   'Número de pessoas com idade entre 25 e 34 anos cadastradas no Cadastro Único':'25-34',
                   'Número de pessoas com idade entre 35 e 39 anos cadastradas no Cadastro Único':'35-39',
                   'Número de pessoas com idade entre 40 e 44 anos cadastradas no Cadastro Único':'40-44',
                   'Número de pessoas com idade entre 45 e 49 anos cadastradas no Cadastro Único':'45-49',
                   'Número de pessoas com idade entre 50 e 54 anos cadastradas no Cadastro Único':'50-54',
                   'Número de pessoas com idade entre 55 e 59 anos cadastradas no Cadastro Único':'55-59',
                   'Número de pessoas com idade entre 60 e 64 anos cadastradas no Cadastro Único':'60-64',
                   'Número de pessoas com idade acima de 64 anos cadastradas no Cadastro Único':'64+',
                   'Número total de pessoas cadastradas no Cadastro Único':'Total'},inplace=True)

df = helper.data_to_ano(df)
df = helper.codigo_to_ri(df)

df = df.drop(columns=['UF','Data','Mes'])

df.head(2)

,Codigo,Municipio,0-3,4-6,7-15,16-17,18-24,25-34,35-39,40-44,45-49,50-54,55-59,60-64,64+,Total,Ano,RI
0,150010,ABAETETUBA,NaN,NaN,23682,5901,17267,16374,6321,5287,4110,3211,2520,1671,2455,88799,2012,Tocantins
1,150010,ABAETETUBA,8003.0,7623.0,22397,5209,16639,22497,9846,7485,9821,6690,5278,3979,6896,132363,2026,Tocantins

In [49]:
df.to_csv('dados_prontos/faixa_etaria_cadunico_tratado.csv',index=False)

In [50]:
df = pd.read_csv('dados_brutos/urbano_rural_cadunico.csv')

df.rename(columns={'Código':'Codigo','Unidade Territorial':'Municipio','Referência':'Data',
'Número de pessoas cadastradas no Cadastro Único em domicílios rurais':'Rural',
'Número de pessoas cadastradas no Cadastro Único em domicílios urbanos':'Urbano'},inplace=True)

df = helper.data_to_ano(df)
df = helper.codigo_to_ri(df)

df = df.drop(columns=['UF','Data','Mes'])

df

       Codigo   Municipio  Rural  Urbano   Ano         RI
0      150010  ABAETETUBA  41681   57453  2012  Tocantins
1      150010  ABAETETUBA  66031   66301  2026  Tocantins
2      150010  ABAETETUBA  66011   66269  2026  Tocantins
3      150010  ABAETETUBA  65893   66235  2026  Tocantins
4      150010  ABAETETUBA  65667   66137  2026  Tocantins
...       ...         ...    ...     ...   ...        ...
24173  150840    XINGUARA   2135   16706  2012   Araguaia
24174  150840    XINGUARA   2162   16641  2012   Araguaia
24175  150840    XINGUARA   2169   16646  2012   Araguaia
24176  150840    XINGUARA   2150   16700  2012   Araguaia
24177  150840    XINGUARA   2151   16729  2012   Araguaia

[24178 rows x 6 columns]

In [51]:
df.to_csv('dados_prontos/urbano_rural_cadunico_tratado.csv')