In [2]:
import pandas as pd

dfEtnia = pd.read_csv('dados_prontos/etnia_cadunico_tratado.csv')


dfEtnia = dfEtnia[dfEtnia['RI'] == 'Guamá']
dfEtniaCenso = dfEtnia[(dfEtnia['Ano'] == 2012) | (dfEtnia['Ano'] == 2022)]
dfEtniaCenso.head(6)

,Codigo,Municipio,Brancos,Pretos,Amarelos,Pardos,Indigenas,NoData,Ano,RI
490,150240,CASTANHAL,10030,3300,213,79294,59,379,2012,Guamá
500,150240,CASTANHAL,13981,4310,369,91126,52,16,2022,Guamá
518,150260,COLARES,656,210,8,6925,2,35,2012,Guamá
528,150260,COLARES,1553,304,44,7652,6,1,2022,Guamá
616,150290,CURUÇÁ,1703,290,70,22630,4,119,2012,Guamá
626,150290,CURUÇÁ,3611,566,155,27544,86,3,2022,Guamá

In [3]:
import pandas as pd
import plotly.express as px

# Categorias que serão visualizadas
categorias = [
    "Brancos",
    "Pretos",
    "Amarelos",
    "Pardos",
    "Indigenas"
]

# Criar dataframe em formato longo
df_long = dfEtniaCenso.melt(
    id_vars=["Codigo", "Municipio", "Ano", "RI"],
    value_vars=categorias,
    var_name="Raça/Cor",
    value_name="Quantidade"
)

fig = px.bar(
    df_long,
    x="Municipio",
    y="Quantidade",
    color="Raça/Cor",
    facet_row="Ano",
    hover_data={
        "Municipio": True,
        "RI": True,
        "Ano": True,
        "Quantidade": ":,.0f"
    },
    title="Composição racial dos municípios do Pará",
    labels={
        "Municipio": "Município",
        "Quantidade": "Quantidade de pessoas",
        "Raça/Cor": "Raça/Cor"
    },
    barmode="group"
)

fig.update_layout(
    height=900,
    xaxis_tickangle=-45,
    legend_title="Raça/Cor",
    hovermode="x unified"
)

fig.show()

In [4]:
dfSexo = pd.read_csv('dados_prontos/sexo_cadunico_tratado.csv')

dfSexoCenso = dfSexo[(dfSexo['Ano'] == 2012) | (dfSexo['Ano'] == 2022)]
dfSexoCenso

      Codigo         Municipio  Homens  Mulheres   Ano         RI
3     150010        ABAETETUBA   62504     70334  2022  Tocantins
13    150010        ABAETETUBA   48019     53970  2012  Tocantins
17    150013   ABEL FIGUEIREDO    2592      3060  2022  Rio Capim
27    150013   ABEL FIGUEIREDO    2198      2594  2012  Rio Capim
31    150020             ACARÁ   22480     25332  2022  Tocantins
...      ...               ...     ...       ...   ...        ...
1983  150830             VISEU   22674     23329  2022  Rio Caeté
1987  150835  VITÓRIA DO XINGU    3668      3767  2012      Xingu
1997  150835  VITÓRIA DO XINGU    5339      6195  2022      Xingu
2004  150840          XINGUARA   11446     14885  2022   Araguaia
2014  150840          XINGUARA    8382     10459  2012   Araguaia

[287 rows x 6 columns]

In [5]:
dfIdade = pd.read_csv('dados_prontos/faixa_etaria_cadunico_tratado.csv')

dfIdadeCenso = dfIdade[(dfIdade['Ano'] == 2012) | (dfIdade['Ano'] == 2022)]
dfIdadeCenso

,Codigo,Municipio,0-3,4-6,7-15,16-17,18-24,25-34,35-39,40-44,45-49,50-54,55-59,60-64,64+,Total,Ano,RI
0,150010,ABAETETUBA,NaN,NaN,23682,5901,17267,16374,6321,5287,4110,3211,2520,1671,2455,88799,2012,Tocantins
44,150010,ABAETETUBA,8359.0,7536.0,22346,5115,18542,22511,9258,8055,6705,5372,4206,2947,5185,126137,2022,Tocantins
45,150010,ABAETETUBA,8444.0,7570.0,22406,5143,18651,22887,9440,8201,6817,5496,4320,3013,5271,127659,2022,Tocantins
46,150010,ABAETETUBA,8475.0,7635.0,22481,5143,18816,23286,9599,8380,6976,5615,4418,3070,5355,129249,2022,Tocantins
47,150010,ABAETETUBA,8279.0,7533.0,22333,5073,18513,22231,9123,7930,6569,5291,4109,2903,5076,124963,2022,Tocantins
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24173,150840,XINGUARA,NaN,NaN,4969,1049,2546,2538,1205,953,743,503,363,373,1332,16574,2012,Araguaia
24174,150840,XINGUARA,NaN,NaN,4959,1061,2530,2521,1205,943,745,495,347,382,1322,16510,2012,Araguaia
24175,150840,XINGUARA,NaN,NaN,4955,1081,2500,2528,1199,951,734,496,344,384,1317,16489,2012,Araguaia
24176,150840,XINGUARA,NaN,NaN,4979,1079,2491,2530,1198,954,725,489,340,391,1305,16481,2012,Araguaia
24177,150840,XINGUARA,NaN,NaN,5018,1065,2476,2530,1195,949,716,488,338,395,1297,16467,2012,Araguaia